// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: service_steamossls.proto

package webui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CSteamOSSLS_GetState_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSteamOSSLS_GetState_Request) Reset() {
	*x = CSteamOSSLS_GetState_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLS_GetState_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLS_GetState_Request) ProtoMessage() {}

func (x *CSteamOSSLS_GetState_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLS_GetState_Request.ProtoReflect.Descriptor instead.
func (*CSteamOSSLS_GetState_Request) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{0}
}

type CSteamOSSLS_GetState_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *CSteamOSSLSState `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (x *CSteamOSSLS_GetState_Response) Reset() {
	*x = CSteamOSSLS_GetState_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLS_GetState_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLS_GetState_Response) ProtoMessage() {}

func (x *CSteamOSSLS_GetState_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLS_GetState_Response.ProtoReflect.Descriptor instead.
func (*CSteamOSSLS_GetState_Response) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{1}
}

func (x *CSteamOSSLS_GetState_Response) GetState() *CSteamOSSLSState {
	if x != nil {
		return x.State
	}
	return nil
}

type CSteamOSSLS_SetEnabled_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled *bool `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
}

func (x *CSteamOSSLS_SetEnabled_Request) Reset() {
	*x = CSteamOSSLS_SetEnabled_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLS_SetEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLS_SetEnabled_Request) ProtoMessage() {}

func (x *CSteamOSSLS_SetEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLS_SetEnabled_Request.ProtoReflect.Descriptor instead.
func (*CSteamOSSLS_SetEnabled_Request) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{2}
}

func (x *CSteamOSSLS_SetEnabled_Request) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CSteamOSSLS_SetEnabled_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSteamOSSLS_SetEnabled_Response) Reset() {
	*x = CSteamOSSLS_SetEnabled_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLS_SetEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLS_SetEnabled_Response) ProtoMessage() {}

func (x *CSteamOSSLS_SetEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLS_SetEnabled_Response.ProtoReflect.Descriptor instead.
func (*CSteamOSSLS_SetEnabled_Response) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{3}
}

type CSteamOSSLS_SetPluginEnabled_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Etype   *int32 `protobuf:"varint,1,opt,name=etype" json:"etype,omitempty"`
	Enabled *bool  `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
}

func (x *CSteamOSSLS_SetPluginEnabled_Request) Reset() {
	*x = CSteamOSSLS_SetPluginEnabled_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLS_SetPluginEnabled_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLS_SetPluginEnabled_Request) ProtoMessage() {}

func (x *CSteamOSSLS_SetPluginEnabled_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLS_SetPluginEnabled_Request.ProtoReflect.Descriptor instead.
func (*CSteamOSSLS_SetPluginEnabled_Request) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{4}
}

func (x *CSteamOSSLS_SetPluginEnabled_Request) GetEtype() int32 {
	if x != nil && x.Etype != nil {
		return *x.Etype
	}
	return 0
}

func (x *CSteamOSSLS_SetPluginEnabled_Request) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CSteamOSSLS_SetPluginEnabled_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSteamOSSLS_SetPluginEnabled_Response) Reset() {
	*x = CSteamOSSLS_SetPluginEnabled_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLS_SetPluginEnabled_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLS_SetPluginEnabled_Response) ProtoMessage() {}

func (x *CSteamOSSLS_SetPluginEnabled_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLS_SetPluginEnabled_Response.ProtoReflect.Descriptor instead.
func (*CSteamOSSLS_SetPluginEnabled_Response) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{5}
}

type CSteamOSSLS_StateChanged_Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSteamOSSLS_StateChanged_Notification) Reset() {
	*x = CSteamOSSLS_StateChanged_Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLS_StateChanged_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLS_StateChanged_Notification) ProtoMessage() {}

func (x *CSteamOSSLS_StateChanged_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLS_StateChanged_Notification.ProtoReflect.Descriptor instead.
func (*CSteamOSSLS_StateChanged_Notification) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{6}
}

type CSteamOSSLSPlugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Etype       *int32 `protobuf:"varint,1,opt,name=etype" json:"etype,omitempty"`
	IsAvailable *bool  `protobuf:"varint,2,opt,name=is_available,json=isAvailable" json:"is_available,omitempty"`
	IsEnabled   *bool  `protobuf:"varint,3,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
}

func (x *CSteamOSSLSPlugin) Reset() {
	*x = CSteamOSSLSPlugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLSPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLSPlugin) ProtoMessage() {}

func (x *CSteamOSSLSPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLSPlugin.ProtoReflect.Descriptor instead.
func (*CSteamOSSLSPlugin) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{7}
}

func (x *CSteamOSSLSPlugin) GetEtype() int32 {
	if x != nil && x.Etype != nil {
		return *x.Etype
	}
	return 0
}

func (x *CSteamOSSLSPlugin) GetIsAvailable() bool {
	if x != nil && x.IsAvailable != nil {
		return *x.IsAvailable
	}
	return false
}

func (x *CSteamOSSLSPlugin) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

type CSteamOSSLSState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAvailable *bool                `protobuf:"varint,1,opt,name=is_available,json=isAvailable" json:"is_available,omitempty"`
	IsEnabled   *bool                `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	Plugins     []*CSteamOSSLSPlugin `protobuf:"bytes,3,rep,name=plugins" json:"plugins,omitempty"`
}

func (x *CSteamOSSLSState) Reset() {
	*x = CSteamOSSLSState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_steamossls_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSteamOSSLSState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSteamOSSLSState) ProtoMessage() {}

func (x *CSteamOSSLSState) ProtoReflect() protoreflect.Message {
	mi := &file_service_steamossls_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSteamOSSLSState.ProtoReflect.Descriptor instead.
func (*CSteamOSSLSState) Descriptor() ([]byte, []int) {
	return file_service_steamossls_proto_rawDescGZIP(), []int{8}
}

func (x *CSteamOSSLSState) GetIsAvailable() bool {
	if x != nil && x.IsAvailable != nil {
		return *x.IsAvailable
	}
	return false
}

func (x *CSteamOSSLSState) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *CSteamOSSLSState) GetPlugins() []*CSteamOSSLSPlugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

var File_service_steamossls_proto protoreflect.FileDescriptor

var file_service_steamossls_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x6f,
	0x73, 0x73, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a,
	0x1c, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a,
	0x1d, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x0a, 0x1e, 0x43, 0x53, 0x74, 0x65, 0x61,
	0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x22, 0x21, 0x0a, 0x1f, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53,
	0x4c, 0x53, 0x5f, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x24, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d,
	0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x05, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x08, 0x82,
	0xb5, 0x18, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x52, 0x05, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x27, 0x0a, 0x25, 0x43, 0x53, 0x74, 0x65,
	0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x27, 0x0a, 0x25, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53,
	0x5f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x5f, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x75, 0x0a, 0x11, 0x43, 0x53,
	0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12,
	0x1e, 0x0a, 0x05, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x08,
	0x82, 0xb5, 0x18, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x52, 0x05, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x22, 0x82, 0x01, 0x0a, 0x10, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c,
	0x53, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x53, 0x74, 0x65,
	0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x07, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x32, 0xd6, 0x02, 0x0a, 0x0a, 0x53, 0x74, 0x65, 0x61, 0x6d,
	0x4f, 0x53, 0x53, 0x4c, 0x53, 0x12, 0x49, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1d, 0x2e, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x26, 0x2e, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f,
	0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0b,
	0x2e, 0x4e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x53,
	0x65, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1f, 0x2e, 0x43, 0x53, 0x74, 0x65,
	0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x43, 0x53, 0x74,
	0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53, 0x65, 0x74, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x10,
	0x53, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x12, 0x25, 0x2e, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53,
	0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x43, 0x53, 0x74, 0x65, 0x61, 0x6d,
	0x4f, 0x53, 0x53, 0x4c, 0x53, 0x5f, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
}

var (
	file_service_steamossls_proto_rawDescOnce sync.Once
	file_service_steamossls_proto_rawDescData = file_service_steamossls_proto_rawDesc
)

func file_service_steamossls_proto_rawDescGZIP() []byte {
	file_service_steamossls_proto_rawDescOnce.Do(func() {
		file_service_steamossls_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_steamossls_proto_rawDescData)
	})
	return file_service_steamossls_proto_rawDescData
}

var file_service_steamossls_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_steamossls_proto_goTypes = []any{
	(*CSteamOSSLS_GetState_Request)(nil),          // 0: CSteamOSSLS_GetState_Request
	(*CSteamOSSLS_GetState_Response)(nil),         // 1: CSteamOSSLS_GetState_Response
	(*CSteamOSSLS_SetEnabled_Request)(nil),        // 2: CSteamOSSLS_SetEnabled_Request
	(*CSteamOSSLS_SetEnabled_Response)(nil),       // 3: CSteamOSSLS_SetEnabled_Response
	(*CSteamOSSLS_SetPluginEnabled_Request)(nil),  // 4: CSteamOSSLS_SetPluginEnabled_Request
	(*CSteamOSSLS_SetPluginEnabled_Response)(nil), // 5: CSteamOSSLS_SetPluginEnabled_Response
	(*CSteamOSSLS_StateChanged_Notification)(nil), // 6: CSteamOSSLS_StateChanged_Notification
	(*CSteamOSSLSPlugin)(nil),                     // 7: CSteamOSSLSPlugin
	(*CSteamOSSLSState)(nil),                      // 8: CSteamOSSLSState
	(*NoResponse)(nil),                            // 9: NoResponse
}
var file_service_steamossls_proto_depIdxs = []int32{
	8, // 0: CSteamOSSLS_GetState_Response.state:type_name -> CSteamOSSLSState
	7, // 1: CSteamOSSLSState.plugins:type_name -> CSteamOSSLSPlugin
	0, // 2: SteamOSSLS.GetState:input_type -> CSteamOSSLS_GetState_Request
	6, // 3: SteamOSSLS.NotifyStateChanged:input_type -> CSteamOSSLS_StateChanged_Notification
	2, // 4: SteamOSSLS.SetEnabled:input_type -> CSteamOSSLS_SetEnabled_Request
	4, // 5: SteamOSSLS.SetPluginEnabled:input_type -> CSteamOSSLS_SetPluginEnabled_Request
	1, // 6: SteamOSSLS.GetState:output_type -> CSteamOSSLS_GetState_Response
	9, // 7: SteamOSSLS.NotifyStateChanged:output_type -> NoResponse
	3, // 8: SteamOSSLS.SetEnabled:output_type -> CSteamOSSLS_SetEnabled_Response
	5, // 9: SteamOSSLS.SetPluginEnabled:output_type -> CSteamOSSLS_SetPluginEnabled_Response
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_steamossls_proto_init() }
func file_service_steamossls_proto_init() {
	if File_service_steamossls_proto != nil {
		return
	}
	file_common_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_steamossls_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLS_GetState_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLS_GetState_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLS_SetEnabled_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLS_SetEnabled_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLS_SetPluginEnabled_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLS_SetPluginEnabled_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLS_StateChanged_Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLSPlugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_steamossls_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CSteamOSSLSState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_steamossls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_steamossls_proto_goTypes,
		DependencyIndexes: file_service_steamossls_proto_depIdxs,
		MessageInfos:      file_service_steamossls_proto_msgTypes,
	}.Build()
	File_service_steamossls_proto = out.File
	file_service_steamossls_proto_rawDesc = nil
	file_service_steamossls_proto_goTypes = nil
	file_service_steamossls_proto_depIdxs = nil
}
