// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: service_transportauth.proto

package webui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CTransportAuth_Authenticate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthKey *string `protobuf:"bytes,1,opt,name=auth_key,json=authKey" json:"auth_key,omitempty"`
}

func (x *CTransportAuth_Authenticate_Request) Reset() {
	*x = CTransportAuth_Authenticate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_transportauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTransportAuth_Authenticate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportAuth_Authenticate_Request) ProtoMessage() {}

func (x *CTransportAuth_Authenticate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_transportauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportAuth_Authenticate_Request.ProtoReflect.Descriptor instead.
func (*CTransportAuth_Authenticate_Request) Descriptor() ([]byte, []int) {
	return file_service_transportauth_proto_rawDescGZIP(), []int{0}
}

func (x *CTransportAuth_Authenticate_Request) GetAuthKey() string {
	if x != nil && x.AuthKey != nil {
		return *x.AuthKey
	}
	return ""
}

type CTransportAuth_Authenticate_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CTransportAuth_Authenticate_Response) Reset() {
	*x = CTransportAuth_Authenticate_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_transportauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTransportAuth_Authenticate_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportAuth_Authenticate_Response) ProtoMessage() {}

func (x *CTransportAuth_Authenticate_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_transportauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportAuth_Authenticate_Response.ProtoReflect.Descriptor instead.
func (*CTransportAuth_Authenticate_Response) Descriptor() ([]byte, []int) {
	return file_service_transportauth_proto_rawDescGZIP(), []int{1}
}

type CTransportAuth_StartShutdown_Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CTransportAuth_StartShutdown_Notification) Reset() {
	*x = CTransportAuth_StartShutdown_Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_transportauth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTransportAuth_StartShutdown_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTransportAuth_StartShutdown_Notification) ProtoMessage() {}

func (x *CTransportAuth_StartShutdown_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_service_transportauth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTransportAuth_StartShutdown_Notification.ProtoReflect.Descriptor instead.
func (*CTransportAuth_StartShutdown_Notification) Descriptor() ([]byte, []int) {
	return file_service_transportauth_proto_rawDescGZIP(), []int{2}
}

var File_service_transportauth_proto protoreflect.FileDescriptor

var file_service_transportauth_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x40, 0x0a, 0x23, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x75,
	0x74, 0x68, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b,
	0x65, 0x79, 0x22, 0x26, 0x0a, 0x24, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x41, 0x75, 0x74, 0x68, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x29, 0x43, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xbc, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x75, 0x74, 0x68, 0x12, 0x5b, 0x0a, 0x0c, 0x41, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x43, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x75, 0x74, 0x68,
	0x5f, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x2a, 0x2e,
	0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x2e, 0x4e, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
}

var (
	file_service_transportauth_proto_rawDescOnce sync.Once
	file_service_transportauth_proto_rawDescData = file_service_transportauth_proto_rawDesc
)

func file_service_transportauth_proto_rawDescGZIP() []byte {
	file_service_transportauth_proto_rawDescOnce.Do(func() {
		file_service_transportauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_transportauth_proto_rawDescData)
	})
	return file_service_transportauth_proto_rawDescData
}

var file_service_transportauth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_transportauth_proto_goTypes = []any{
	(*CTransportAuth_Authenticate_Request)(nil),       // 0: CTransportAuth_Authenticate_Request
	(*CTransportAuth_Authenticate_Response)(nil),      // 1: CTransportAuth_Authenticate_Response
	(*CTransportAuth_StartShutdown_Notification)(nil), // 2: CTransportAuth_StartShutdown_Notification
	(*NoResponse)(nil), // 3: NoResponse
}
var file_service_transportauth_proto_depIdxs = []int32{
	0, // 0: TransportAuth.Authenticate:input_type -> CTransportAuth_Authenticate_Request
	2, // 1: TransportAuth.NotifyStartShutdown:input_type -> CTransportAuth_StartShutdown_Notification
	1, // 2: TransportAuth.Authenticate:output_type -> CTransportAuth_Authenticate_Response
	3, // 3: TransportAuth.NotifyStartShutdown:output_type -> NoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_transportauth_proto_init() }
func file_service_transportauth_proto_init() {
	if File_service_transportauth_proto != nil {
		return
	}
	file_common_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_transportauth_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CTransportAuth_Authenticate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_transportauth_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CTransportAuth_Authenticate_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_transportauth_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CTransportAuth_StartShutdown_Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_transportauth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_transportauth_proto_goTypes,
		DependencyIndexes: file_service_transportauth_proto_depIdxs,
		MessageInfos:      file_service_transportauth_proto_msgTypes,
	}.Build()
	File_service_transportauth_proto = out.File
	file_service_transportauth_proto_rawDesc = nil
	file_service_transportauth_proto_goTypes = nil
	file_service_transportauth_proto_depIdxs = nil
}
