// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: service_clanchatrooms.proto

package webui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CClanChatRooms_GetClanChatRoomInfo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steamid    *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Autocreate *bool   `protobuf:"varint,2,opt,name=autocreate,def=1" json:"autocreate,omitempty"`
}

// Default values for CClanChatRooms_GetClanChatRoomInfo_Request fields.
const (
	Default_CClanChatRooms_GetClanChatRoomInfo_Request_Autocreate = bool(true)
)

func (x *CClanChatRooms_GetClanChatRoomInfo_Request) Reset() {
	*x = CClanChatRooms_GetClanChatRoomInfo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_clanchatrooms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CClanChatRooms_GetClanChatRoomInfo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CClanChatRooms_GetClanChatRoomInfo_Request) ProtoMessage() {}

func (x *CClanChatRooms_GetClanChatRoomInfo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_clanchatrooms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CClanChatRooms_GetClanChatRoomInfo_Request.ProtoReflect.Descriptor instead.
func (*CClanChatRooms_GetClanChatRoomInfo_Request) Descriptor() ([]byte, []int) {
	return file_service_clanchatrooms_proto_rawDescGZIP(), []int{0}
}

func (x *CClanChatRooms_GetClanChatRoomInfo_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CClanChatRooms_GetClanChatRoomInfo_Request) GetAutocreate() bool {
	if x != nil && x.Autocreate != nil {
		return *x.Autocreate
	}
	return Default_CClanChatRooms_GetClanChatRoomInfo_Request_Autocreate
}

type CClanChatRooms_GetClanChatRoomInfo_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatGroupSummary *CChatRoom_GetChatRoomGroupSummary_Response `protobuf:"bytes,1,opt,name=chat_group_summary,json=chatGroupSummary" json:"chat_group_summary,omitempty"`
}

func (x *CClanChatRooms_GetClanChatRoomInfo_Response) Reset() {
	*x = CClanChatRooms_GetClanChatRoomInfo_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_clanchatrooms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CClanChatRooms_GetClanChatRoomInfo_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CClanChatRooms_GetClanChatRoomInfo_Response) ProtoMessage() {}

func (x *CClanChatRooms_GetClanChatRoomInfo_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_clanchatrooms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CClanChatRooms_GetClanChatRoomInfo_Response.ProtoReflect.Descriptor instead.
func (*CClanChatRooms_GetClanChatRoomInfo_Response) Descriptor() ([]byte, []int) {
	return file_service_clanchatrooms_proto_rawDescGZIP(), []int{1}
}

func (x *CClanChatRooms_GetClanChatRoomInfo_Response) GetChatGroupSummary() *CChatRoom_GetChatRoomGroupSummary_Response {
	if x != nil {
		return x.ChatGroupSummary
	}
	return nil
}

type CClanChatRooms_SetClanChatRoomPrivate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steamid         *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ChatRoomPrivate *bool   `protobuf:"varint,2,opt,name=chat_room_private,json=chatRoomPrivate" json:"chat_room_private,omitempty"`
}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Request) Reset() {
	*x = CClanChatRooms_SetClanChatRoomPrivate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_clanchatrooms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CClanChatRooms_SetClanChatRoomPrivate_Request) ProtoMessage() {}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_clanchatrooms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CClanChatRooms_SetClanChatRoomPrivate_Request.ProtoReflect.Descriptor instead.
func (*CClanChatRooms_SetClanChatRoomPrivate_Request) Descriptor() ([]byte, []int) {
	return file_service_clanchatrooms_proto_rawDescGZIP(), []int{2}
}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Request) GetChatRoomPrivate() bool {
	if x != nil && x.ChatRoomPrivate != nil {
		return *x.ChatRoomPrivate
	}
	return false
}

type CClanChatRooms_SetClanChatRoomPrivate_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatRoomPrivate *bool `protobuf:"varint,1,opt,name=chat_room_private,json=chatRoomPrivate" json:"chat_room_private,omitempty"`
}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Response) Reset() {
	*x = CClanChatRooms_SetClanChatRoomPrivate_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_clanchatrooms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CClanChatRooms_SetClanChatRoomPrivate_Response) ProtoMessage() {}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_clanchatrooms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CClanChatRooms_SetClanChatRoomPrivate_Response.ProtoReflect.Descriptor instead.
func (*CClanChatRooms_SetClanChatRoomPrivate_Response) Descriptor() ([]byte, []int) {
	return file_service_clanchatrooms_proto_rawDescGZIP(), []int{3}
}

func (x *CClanChatRooms_SetClanChatRoomPrivate_Response) GetChatRoomPrivate() bool {
	if x != nil && x.ChatRoomPrivate != nil {
		return *x.ChatRoomPrivate
	}
	return false
}

var File_service_clanchatrooms_proto protoreflect.FileDescriptor

var file_service_clanchatrooms_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x6e, 0x63, 0x68,
	0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x2a, 0x43,
	0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x47, 0x65,
	0x74, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x65,
	0x61, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x73, 0x74, 0x65, 0x61,
	0x6d, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52, 0x0a, 0x61,
	0x75, 0x74, 0x6f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x2b, 0x43, 0x43,
	0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x47, 0x65, 0x74,
	0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x12, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x43, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x5f, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x10, 0x63, 0x68, 0x61, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x22, 0x75, 0x0a, 0x2d, 0x43, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x12,
	0x2a, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x5c, 0x0a, 0x2e, 0x43,
	0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x53, 0x65,
	0x74, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x11, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x32, 0xfc, 0x01, 0x0a, 0x0d, 0x43, 0x6c,
	0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x70, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2b, 0x2e, 0x43, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x5f, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x43, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73,
	0x5f, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x79, 0x0a,
	0x16, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x2e, 0x43, 0x43, 0x6c, 0x61, 0x6e, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x6e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x43, 0x43, 0x6c, 0x61, 0x6e, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x6e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
}

var (
	file_service_clanchatrooms_proto_rawDescOnce sync.Once
	file_service_clanchatrooms_proto_rawDescData = file_service_clanchatrooms_proto_rawDesc
)

func file_service_clanchatrooms_proto_rawDescGZIP() []byte {
	file_service_clanchatrooms_proto_rawDescOnce.Do(func() {
		file_service_clanchatrooms_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_clanchatrooms_proto_rawDescData)
	})
	return file_service_clanchatrooms_proto_rawDescData
}

var file_service_clanchatrooms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_clanchatrooms_proto_goTypes = []any{
	(*CClanChatRooms_GetClanChatRoomInfo_Request)(nil),     // 0: CClanChatRooms_GetClanChatRoomInfo_Request
	(*CClanChatRooms_GetClanChatRoomInfo_Response)(nil),    // 1: CClanChatRooms_GetClanChatRoomInfo_Response
	(*CClanChatRooms_SetClanChatRoomPrivate_Request)(nil),  // 2: CClanChatRooms_SetClanChatRoomPrivate_Request
	(*CClanChatRooms_SetClanChatRoomPrivate_Response)(nil), // 3: CClanChatRooms_SetClanChatRoomPrivate_Response
	(*CChatRoom_GetChatRoomGroupSummary_Response)(nil),     // 4: CChatRoom_GetChatRoomGroupSummary_Response
}
var file_service_clanchatrooms_proto_depIdxs = []int32{
	4, // 0: CClanChatRooms_GetClanChatRoomInfo_Response.chat_group_summary:type_name -> CChatRoom_GetChatRoomGroupSummary_Response
	0, // 1: ClanChatRooms.GetClanChatRoomInfo:input_type -> CClanChatRooms_GetClanChatRoomInfo_Request
	2, // 2: ClanChatRooms.SetClanChatRoomPrivate:input_type -> CClanChatRooms_SetClanChatRoomPrivate_Request
	1, // 3: ClanChatRooms.GetClanChatRoomInfo:output_type -> CClanChatRooms_GetClanChatRoomInfo_Response
	3, // 4: ClanChatRooms.SetClanChatRoomPrivate:output_type -> CClanChatRooms_SetClanChatRoomPrivate_Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_clanchatrooms_proto_init() }
func file_service_clanchatrooms_proto_init() {
	if File_service_clanchatrooms_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_clanchatrooms_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CClanChatRooms_GetClanChatRoomInfo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_clanchatrooms_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CClanChatRooms_GetClanChatRoomInfo_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_clanchatrooms_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CClanChatRooms_SetClanChatRoomPrivate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_clanchatrooms_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CClanChatRooms_SetClanChatRoomPrivate_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_clanchatrooms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_clanchatrooms_proto_goTypes,
		DependencyIndexes: file_service_clanchatrooms_proto_depIdxs,
		MessageInfos:      file_service_clanchatrooms_proto_msgTypes,
	}.Build()
	File_service_clanchatrooms_proto = out.File
	file_service_clanchatrooms_proto_rawDesc = nil
	file_service_clanchatrooms_proto_goTypes = nil
	file_service_clanchatrooms_proto_depIdxs = nil
}
