// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: service_sharedjscontext.proto

package webui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgSteamUIBrowserWindow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pid                   *int32  `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	BrowserId             *int32  `protobuf:"varint,3,opt,name=browser_id,json=browserId" json:"browser_id,omitempty"`
	WindowType            *int32  `protobuf:"varint,4,opt,name=window_type,json=windowType" json:"window_type,omitempty"`
	X                     *int32  `protobuf:"varint,5,opt,name=x" json:"x,omitempty"`
	Y                     *int32  `protobuf:"varint,6,opt,name=y" json:"y,omitempty"`
	Appid                 *uint64 `protobuf:"varint,7,opt,name=appid" json:"appid,omitempty"`
	ParentWindowHandle    *uint64 `protobuf:"varint,8,opt,name=parent_window_handle,json=parentWindowHandle" json:"parent_window_handle,omitempty"`
	AppName               *string `protobuf:"bytes,9,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	GamepaduiViaGamescope *bool   `protobuf:"varint,10,opt,name=gamepadui_via_gamescope,json=gamepaduiViaGamescope" json:"gamepadui_via_gamescope,omitempty"`
}

func (x *CMsgSteamUIBrowserWindow) Reset() {
	*x = CMsgSteamUIBrowserWindow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_sharedjscontext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMsgSteamUIBrowserWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSteamUIBrowserWindow) ProtoMessage() {}

func (x *CMsgSteamUIBrowserWindow) ProtoReflect() protoreflect.Message {
	mi := &file_service_sharedjscontext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSteamUIBrowserWindow.ProtoReflect.Descriptor instead.
func (*CMsgSteamUIBrowserWindow) Descriptor() ([]byte, []int) {
	return file_service_sharedjscontext_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgSteamUIBrowserWindow) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetPid() int32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetBrowserId() int32 {
	if x != nil && x.BrowserId != nil {
		return *x.BrowserId
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetWindowType() int32 {
	if x != nil && x.WindowType != nil {
		return *x.WindowType
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetAppid() uint64 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetParentWindowHandle() uint64 {
	if x != nil && x.ParentWindowHandle != nil {
		return *x.ParentWindowHandle
	}
	return 0
}

func (x *CMsgSteamUIBrowserWindow) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *CMsgSteamUIBrowserWindow) GetGamepaduiViaGamescope() bool {
	if x != nil && x.GamepaduiViaGamescope != nil {
		return *x.GamepaduiViaGamescope
	}
	return false
}

type CSharedJSContext_GetDesiredSteamUIWindows_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CSharedJSContext_GetDesiredSteamUIWindows_Request) Reset() {
	*x = CSharedJSContext_GetDesiredSteamUIWindows_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_sharedjscontext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSharedJSContext_GetDesiredSteamUIWindows_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSharedJSContext_GetDesiredSteamUIWindows_Request) ProtoMessage() {}

func (x *CSharedJSContext_GetDesiredSteamUIWindows_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_sharedjscontext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSharedJSContext_GetDesiredSteamUIWindows_Request.ProtoReflect.Descriptor instead.
func (*CSharedJSContext_GetDesiredSteamUIWindows_Request) Descriptor() ([]byte, []int) {
	return file_service_sharedjscontext_proto_rawDescGZIP(), []int{1}
}

type CSharedJSContext_GetDesiredSteamUIWindows_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Windows []*CMsgSteamUIBrowserWindow `protobuf:"bytes,1,rep,name=windows" json:"windows,omitempty"`
}

func (x *CSharedJSContext_GetDesiredSteamUIWindows_Response) Reset() {
	*x = CSharedJSContext_GetDesiredSteamUIWindows_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_sharedjscontext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSharedJSContext_GetDesiredSteamUIWindows_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSharedJSContext_GetDesiredSteamUIWindows_Response) ProtoMessage() {}

func (x *CSharedJSContext_GetDesiredSteamUIWindows_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_sharedjscontext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSharedJSContext_GetDesiredSteamUIWindows_Response.ProtoReflect.Descriptor instead.
func (*CSharedJSContext_GetDesiredSteamUIWindows_Response) Descriptor() ([]byte, []int) {
	return file_service_sharedjscontext_proto_rawDescGZIP(), []int{2}
}

func (x *CSharedJSContext_GetDesiredSteamUIWindows_Response) GetWindows() []*CMsgSteamUIBrowserWindow {
	if x != nil {
		return x.Windows
	}
	return nil
}

var File_service_sharedjscontext_proto protoreflect.FileDescriptor

var file_service_sharedjscontext_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x6a, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb3, 0x02, 0x0a, 0x18, 0x43, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x55, 0x49, 0x42,
	0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64,
	0x12, 0x30, 0x0a, 0x14, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a,
	0x17, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x61, 0x64, 0x75, 0x69, 0x5f, 0x76, 0x69, 0x61, 0x5f, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15,
	0x67, 0x61, 0x6d, 0x65, 0x70, 0x61, 0x64, 0x75, 0x69, 0x56, 0x69, 0x61, 0x47, 0x61, 0x6d, 0x65,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x31, 0x43, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x4a, 0x53, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73,
	0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x55, 0x49, 0x57, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x69, 0x0a, 0x32, 0x43, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x4a, 0x53, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x55, 0x49,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x43, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x55, 0x49, 0x42,
	0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x07, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x73, 0x32, 0x97, 0x01, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x4a, 0x53, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x83, 0x01, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x55, 0x49, 0x57,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x12, 0x32, 0x2e, 0x43, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x4a, 0x53, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73,
	0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x55, 0x49, 0x57, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x43, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x4a, 0x53, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x55, 0x49, 0x57,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
}

var (
	file_service_sharedjscontext_proto_rawDescOnce sync.Once
	file_service_sharedjscontext_proto_rawDescData = file_service_sharedjscontext_proto_rawDesc
)

func file_service_sharedjscontext_proto_rawDescGZIP() []byte {
	file_service_sharedjscontext_proto_rawDescOnce.Do(func() {
		file_service_sharedjscontext_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_sharedjscontext_proto_rawDescData)
	})
	return file_service_sharedjscontext_proto_rawDescData
}

var file_service_sharedjscontext_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_sharedjscontext_proto_goTypes = []any{
	(*CMsgSteamUIBrowserWindow)(nil),                           // 0: CMsgSteamUIBrowserWindow
	(*CSharedJSContext_GetDesiredSteamUIWindows_Request)(nil),  // 1: CSharedJSContext_GetDesiredSteamUIWindows_Request
	(*CSharedJSContext_GetDesiredSteamUIWindows_Response)(nil), // 2: CSharedJSContext_GetDesiredSteamUIWindows_Response
}
var file_service_sharedjscontext_proto_depIdxs = []int32{
	0, // 0: CSharedJSContext_GetDesiredSteamUIWindows_Response.windows:type_name -> CMsgSteamUIBrowserWindow
	1, // 1: SharedJSContext.GetDesiredSteamUIWindows:input_type -> CSharedJSContext_GetDesiredSteamUIWindows_Request
	2, // 2: SharedJSContext.GetDesiredSteamUIWindows:output_type -> CSharedJSContext_GetDesiredSteamUIWindows_Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_sharedjscontext_proto_init() }
func file_service_sharedjscontext_proto_init() {
	if File_service_sharedjscontext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_sharedjscontext_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CMsgSteamUIBrowserWindow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_sharedjscontext_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CSharedJSContext_GetDesiredSteamUIWindows_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_sharedjscontext_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CSharedJSContext_GetDesiredSteamUIWindows_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_sharedjscontext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_sharedjscontext_proto_goTypes,
		DependencyIndexes: file_service_sharedjscontext_proto_depIdxs,
		MessageInfos:      file_service_sharedjscontext_proto_msgTypes,
	}.Build()
	File_service_sharedjscontext_proto = out.File
	file_service_sharedjscontext_proto_rawDesc = nil
	file_service_sharedjscontext_proto_goTypes = nil
	file_service_sharedjscontext_proto_depIdxs = nil
}
