// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: service_embedded.proto

package webui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CEmbeddedClient_AuthorizeCurrentDevice_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steamid    *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid      *uint32 `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	DeviceInfo *string `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`
	Deviceid   *uint32 `protobuf:"varint,4,opt,name=deviceid" json:"deviceid,omitempty"`
}

func (x *CEmbeddedClient_AuthorizeCurrentDevice_Request) Reset() {
	*x = CEmbeddedClient_AuthorizeCurrentDevice_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_embedded_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CEmbeddedClient_AuthorizeCurrentDevice_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEmbeddedClient_AuthorizeCurrentDevice_Request) ProtoMessage() {}

func (x *CEmbeddedClient_AuthorizeCurrentDevice_Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_embedded_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEmbeddedClient_AuthorizeCurrentDevice_Request.ProtoReflect.Descriptor instead.
func (*CEmbeddedClient_AuthorizeCurrentDevice_Request) Descriptor() ([]byte, []int) {
	return file_service_embedded_proto_rawDescGZIP(), []int{0}
}

func (x *CEmbeddedClient_AuthorizeCurrentDevice_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CEmbeddedClient_AuthorizeCurrentDevice_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CEmbeddedClient_AuthorizeCurrentDevice_Request) GetDeviceInfo() string {
	if x != nil && x.DeviceInfo != nil {
		return *x.DeviceInfo
	}
	return ""
}

func (x *CEmbeddedClient_AuthorizeCurrentDevice_Request) GetDeviceid() uint32 {
	if x != nil && x.Deviceid != nil {
		return *x.Deviceid
	}
	return 0
}

type CEmbeddedClient_AuthorizeDevice_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *uint32                `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Token  *CEmbeddedClient_Token `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (x *CEmbeddedClient_AuthorizeDevice_Response) Reset() {
	*x = CEmbeddedClient_AuthorizeDevice_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_embedded_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CEmbeddedClient_AuthorizeDevice_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEmbeddedClient_AuthorizeDevice_Response) ProtoMessage() {}

func (x *CEmbeddedClient_AuthorizeDevice_Response) ProtoReflect() protoreflect.Message {
	mi := &file_service_embedded_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEmbeddedClient_AuthorizeDevice_Response.ProtoReflect.Descriptor instead.
func (*CEmbeddedClient_AuthorizeDevice_Response) Descriptor() ([]byte, []int) {
	return file_service_embedded_proto_rawDescGZIP(), []int{1}
}

func (x *CEmbeddedClient_AuthorizeDevice_Response) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *CEmbeddedClient_AuthorizeDevice_Response) GetToken() *CEmbeddedClient_Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type CEmbeddedClient_Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steamid     *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ClientToken []byte  `protobuf:"bytes,2,opt,name=client_token,json=clientToken" json:"client_token,omitempty"`
	Expiry      *uint32 `protobuf:"varint,3,opt,name=expiry" json:"expiry,omitempty"`
	Deviceid    *uint32 `protobuf:"varint,4,opt,name=deviceid" json:"deviceid,omitempty"`
}

func (x *CEmbeddedClient_Token) Reset() {
	*x = CEmbeddedClient_Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_embedded_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CEmbeddedClient_Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEmbeddedClient_Token) ProtoMessage() {}

func (x *CEmbeddedClient_Token) ProtoReflect() protoreflect.Message {
	mi := &file_service_embedded_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEmbeddedClient_Token.ProtoReflect.Descriptor instead.
func (*CEmbeddedClient_Token) Descriptor() ([]byte, []int) {
	return file_service_embedded_proto_rawDescGZIP(), []int{2}
}

func (x *CEmbeddedClient_Token) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CEmbeddedClient_Token) GetClientToken() []byte {
	if x != nil {
		return x.ClientToken
	}
	return nil
}

func (x *CEmbeddedClient_Token) GetExpiry() uint32 {
	if x != nil && x.Expiry != nil {
		return *x.Expiry
	}
	return 0
}

func (x *CEmbeddedClient_Token) GetDeviceid() uint32 {
	if x != nil && x.Deviceid != nil {
		return *x.Deviceid
	}
	return 0
}

var File_service_embedded_proto protoreflect.FileDescriptor

var file_service_embedded_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x2e, 0x43, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x73, 0x74,
	0x65, 0x61, 0x6d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x28, 0x43, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x43, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x15, 0x43,
	0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x69, 0x64, 0x32, 0x86, 0x01, 0x0a, 0x0e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x74, 0x0a, 0x16, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2f, 0x2e, 0x43, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x43, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
}

var (
	file_service_embedded_proto_rawDescOnce sync.Once
	file_service_embedded_proto_rawDescData = file_service_embedded_proto_rawDesc
)

func file_service_embedded_proto_rawDescGZIP() []byte {
	file_service_embedded_proto_rawDescOnce.Do(func() {
		file_service_embedded_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_embedded_proto_rawDescData)
	})
	return file_service_embedded_proto_rawDescData
}

var file_service_embedded_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_embedded_proto_goTypes = []any{
	(*CEmbeddedClient_AuthorizeCurrentDevice_Request)(nil), // 0: CEmbeddedClient_AuthorizeCurrentDevice_Request
	(*CEmbeddedClient_AuthorizeDevice_Response)(nil),       // 1: CEmbeddedClient_AuthorizeDevice_Response
	(*CEmbeddedClient_Token)(nil),                          // 2: CEmbeddedClient_Token
}
var file_service_embedded_proto_depIdxs = []int32{
	2, // 0: CEmbeddedClient_AuthorizeDevice_Response.token:type_name -> CEmbeddedClient_Token
	0, // 1: EmbeddedClient.AuthorizeCurrentDevice:input_type -> CEmbeddedClient_AuthorizeCurrentDevice_Request
	1, // 2: EmbeddedClient.AuthorizeCurrentDevice:output_type -> CEmbeddedClient_AuthorizeDevice_Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_embedded_proto_init() }
func file_service_embedded_proto_init() {
	if File_service_embedded_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_embedded_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CEmbeddedClient_AuthorizeCurrentDevice_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_embedded_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CEmbeddedClient_AuthorizeDevice_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_embedded_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CEmbeddedClient_Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_embedded_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_embedded_proto_goTypes,
		DependencyIndexes: file_service_embedded_proto_depIdxs,
		MessageInfos:      file_service_embedded_proto_msgTypes,
	}.Build()
	File_service_embedded_proto = out.File
	file_service_embedded_proto_rawDesc = nil
	file_service_embedded_proto_goTypes = nil
	file_service_embedded_proto_depIdxs = nil
}
